Improve message when directory is passed dotc.
Previously, running ./bin/dotc <directory> caused a null pointer
exception. Now, the error is:

  error: expected file, received directory 'bin'