Support derivation for self-based type classes (#26719)
Self-based type classes, e.g.

```scala
trait TC:
  type Self
  def apply(): Self

given Int is TC = () => 42
```

doesn't support derivation

```scala
object TC:
  def derived[X]: X is TC = ???

  case class C() derives TC
```

error: `type TC in derives clause of C has no type parameters`

It can be achieved via
```scala
given C is TC = TC.derived
```

But imo, to make modularity changes comprehensive, derivation should be
supported (similarly to the context bounds).

It works when `modularity` flag imported.

## Have you relied on LLM-based tools in this contribution?

<!-- Pick one; "running tests" is not enough; refer to
https://github.com/scala/scala3/blob/main/LLM_POLICY.md for details -->

Yes, and I've verified the output.

## How was the solution tested?

<!-- Pick one; exceptions must have a very good reason -->

New automated tests