add type parameter in foreachKey and foreachValue
useful if parameter does not return `Unit` type

```
Welcome to Scala 2.13.0-M4 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_181).
Type in expressions for evaluation. Or try :help.

scala> def f[A]: A => A = { x => println(x); x }
f: [A]=> A => A

scala> collection.mutable.AnyRefMap("a" -> "b").foreachKey(f)
a

scala> collection.immutable.IntMap(1 -> 2).foreachKey(f)
                                                      ^
       error: type mismatch;
        found   : scala.collection.immutable.IntMapUtils.Int => scala.collection.immutable.IntMapUtils.Int
           (which expands to)  Int => Int
        required: scala.collection.immutable.IntMapUtils.Int => Unit
           (which expands to)  Int => Unit

scala> collection.immutable.IntMap(1 -> 2).foreachKey(f(_))
1
```