Tighten signature of ImmutableArray.unsafeWrapArray
Otherwise, type inference will compute `ImmutableArray[Nothing]` in
cases where there's no expected type. Before this change:

    scala> collection.immutable.ImmutableArray.unsafeWrapArray(Array(1)).head
    java.lang.ClassCastException: java.lang.Integer cannot be cast to scala.runtime.Nothing$

The new signature requires additional casts at the use-site. The tricky
case is when there's an array of boxed primitives, and the user would
like to get an `ImmutableArray[Int]`. The following crashes:

    scala> val a: Array[Any] = Array(1)
    a: Array[Any] = Array(1)

    scala> collection.immutable.ImmutableArray.unsafeWrapArray(a.asInstanceOf[Array[Int]])
    java.lang.ClassCastException: [Ljava.lang.Object; cannot be cast to [I

Instead, the user has to cast the resulting `ImmutableArray`:

    scala> collection.immutable.ImmutableArray.unsafeWrapArray(a).asInstanceOf[collection.immutable.ImmutableArray[Int]]
    res3: scala.collection.immutable.ImmutableArray[Int] = ImmutableArray(1)