Fix typo in JavaConverters doc
There is no such thing as scala.collection.mutable.concurrent.Map

    error: object concurrent is not a member of package scala.collection.mutable

Introduced in 7497957e