Fix scaladoc Try.fold example
remove Throwable from the method's return type signature 
( previously borrowed probably from Either[Throwable, T] ) 
because of: 
error: wrong number of type arguments for scala.util.Try, should be 1