Adjust the API name entry for nested classes
**Problem**
Some build pipelining tests fail on the latest sbt RC.

```
Error:  (sbt-test / scripted) Failed tests:
Error:  	pipelining/Yjava-tasty-fromjavaobject
Error:  	pipelining/Yjava-tasty-paths
```

This is likely caused by inconsistent capturing of APIs
from Java sources in ExtractAPI vs AnalyzingJavaCompiler in Zinc.

**Solution**
This adjusts the API name entry for Java nested classes.

[Cherry-picked accf42d555a6754a620b56fbaec604df1d89a469]