Disable flakey test
We get occasional failures of the form

java.lang.AssertionError: assertion failed: asTerm called on not-a-Term val <none> while compiling tests/pos/projections.scala
Fatal compiler crash when compiling: tests/pos/projections.scala:
assertion failed: asTerm called on not-a-Term val <none>
dotty.DottyPredef$.assertFail(DottyPredef.scala:17)
dotty.tools.dotc.core.Symbols$Symbol.asTerm(Symbols.scala:156)

when compiling pos/projections.scala with FromTasty tests.

It was first observed when we parallelized position pickling, so it might have something to do with that.