fix benchmarks exception
The benchmark project generates a dubious exception when compiling
scala stdlib:

    java.lang.ClassCastException: scala.tools.nsc.backend.jvm.BTypes$ClassBType
    cannot be cast to scala.tools.nsc.backend.jvm.BTypes$ArrayBType

Upon investigation, this turns out to be a backend incompatibility
problem. The bench project runs with a previous version of scala-compiler.
Explicitly designating the scala-compiler version for bench fixes
the problem.