Fix regression #26374: generic signatures of mixed-in trait setters
Fixes #26531
Fixes #26533

This is the fix for the regression introduced by #26374

**original issue #26372**

The original issue #26372 was, given:

```scala
trait MyTrait[S0]:
  val foo: Map[S0, String]

abstract class MyAbstract[S1] extends MyTrait[S1]
```

`Mixin` copies the setter of `MyTrait` into `MyAbstract`, and it's
expected type is like `def foo_=(value: Map[S1, String]): Unit`.

However, `mixinGenericInfos` in `Mixin.scala`, construct generic
information from trait as-is.
`def foo_=(value: Map[S0, String]): Unit` (insttead of `S1`),
where `S0` is not declared in `MyAbstract[S1]` scope.

As a result, `GenericSignatures` tells that `S1` isn't referenceable
from `MyAbstract`, and widen to it's upper bound `Any`.
In the end, generic signature for generated setter for `MyTrait` became
`Map<Object, String>` that isn't compatible with `MyTrait`'s setter
and fails with

```java
MyJavaImpl.java:3: error: MyJavaImpl is not abstract and does not override abstract method test$MyTrait$_setter_$test$MyTrait$$myMap_$eq(scala.collection.mutable.Map<java.lang.Object,java.lang.String>) in MyTrait
public class MyJavaImpl extends MyAbstract<String> {
       ^
```

---

**How #26374 address the issue**

the fix by #26374 was "if it's a type parameter,
don't widen it, just output the name as-is" by:

```scala
if typeSym.isTypeParam then
  typeParamSig(typeSym.name)
```

result in `Map<S1, String>`

---

**Why #26374 introduced regressions**

However, in a JVM signature can only be written when the enclosing
class or method actually declares tparam `S1`.

For #26533

```scala
class Wrap[A](val value: G[A]) extends AnyVal
class FirstList(val cache: Cache[Wrap])
```

`A` is declared only within `Wrap`. `FirstList` does not declare `A`.
However, `A` is still type parameter and `isTypeParam` returns true.
Therefore, it ended up emitting `Cache<G<TA;>>` where A isn't declared
in `FirstList` scope.

For #26351

```scala
class Builder[T] { def accept[M <: T] }
```

`tp.typeSymbol` looks it's underlying/bound instead of the type
parameter itself. So, `M <: T` became `T`.

---

**How this commit fix**

The real problem is in earlier on the pipeline, before `GenericSignatures`.
When `Mixin` copies the setter, owner and type info as-is from parent.
(`MyAbstract`'s setter still `Map[MyTrait.S, String]`, but it should be
`Map[MyAbstract.S, String]`).

This time, we use `asSeenFrom` for `mixinGenericInfo`
so the setter type is `MyTrait`.