Upgrade ruby version in spec.yml
Solves
```
Run gem update --system
ERROR:  Error installing rubygems-update:
	There are no versions of rubygems-update (= 3.5.1) compatible with your Ruby & RubyGems
	rubygems-update requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.225.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
Updating rubygems-update
```